params:
  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512]
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None
    rnn:
        name: lstm
        units: 1024
        layers: 1
        before_mlp: True
        layer_norm: True
  config:
    central_value_config:
      minibatch_size: ${..minibatch_size}
      mini_epochs: ${..mini_epochs}
      learning_rate: ${..learning_rate} # 3.e-4
      lr_schedule: ${..lr_schedule} # adaptive
      schedule_type: standard
      kl_threshold: ${..kl_threshold} # 0.008
      clip_value: True
      normalize_input: True
      truncate_grads: ${..truncate_grads}

      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [512]
          activation: relu
          d2rl: False
          initializer:
            name: default
          regularizer:
            name: None
        rnn:
            name: lstm
            units: 1024
            layers: 1
            before_mlp: True
            layer_norm: True
    # num_actors: ${....task.env.numEnvs} # seems to be not needed
    name: ${resolve_default:BipedAsymmLSTM,${....experiment}}
    # value_bootstrap: False # doe not seems to help too much
    # mixed_precision: False


defaults:
  - LeggedTerrainPPO
  - _self_